import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { Activity, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Download, Dumbbell, Flame, History, Info, LayoutDashboard, Menu, Plus, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, Trash2, TrendingUp, Trophy, X } from 'lucide-react';
import { DEFAULT_SETTINGS, EXERCISES, MUSCLES, balanceScore, buildBalancePlan, demoWorkouts, estimatedOneRepMax, exerciseById, fmt, localDate, makeSets, makeWorkout, muscleLoad, volume, weekStart, workingSets, type Equipment, type Muscle, type Settings, type Workout } from './lib/model';
import BodyMap, { loadColor } from './components/BodyMap';
import { VolumeChart, Sparkline } from './components/Charts';
import Modal from './components/Modal';
import WorkoutView, { type Draft } from './components/WorkoutView';
import { useTrainingTools } from './lib/webmcp';

type View = 'overview' | 'workout' | 'history' | 'library' | 'progress';
const NAV = [{ id: 'overview', label: 'Обзор', icon: LayoutDashboard }, { id: 'workout', label: 'Тренировка', icon: Dumbbell }, { id: 'history', label: 'История', icon: History }, { id: 'library', label: 'Упражнения', icon: Activity }, { id: 'progress', label: 'Прогресс', icon: BarChart3 }] as const;
const EQ = { gym: 'Весь зал', dumbbells: 'Гантели', bodyweight: 'Без оборудования' };
const dateLabel = (date: string, long = false) => new Date(date + 'T12:00:00').toLocaleDateString('ru-RU', { day: 'numeric', month: long ? 'long' : 'short' });
const readDraft = (): Draft | null => { try { const d = JSON.parse(localStorage.getItem('tyaga-draft-v1') ?? 'null'); if (!d || !d.workout || !Array.isArray(d.workout.exercises) || !Number.isFinite(d.startedAt)) return null; if (d.workout.exercises.some((e: { exerciseId: string; sets: unknown }) => !exerciseById(e.exerciseId) || !Array.isArray(e.sets))) return null; return d; } catch { return null; } };
async function api<T>(path: string, method = 'GET', body?: unknown, signal?: AbortSignal): Promise<T> {
  const response = await fetch(path, { method, signal, headers: method === 'GET' ? {} : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? 'Не удалось выполнить запрос'); return data;
}

export default function App() {
  const [view, setView] = useState<View>('overview');
  const [workouts, setWorkouts] = useState<Workout[]>([]);
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState('');
  const [demo, setDemo] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(readDraft);
  const [mobileNav, setMobileNav] = useState(false);
  const [toast, setToast] = useState('');
  const [modal, setModal] = useState<'picker' | 'planner' | 'settings' | 'method' | 'discard' | null>(null);
  const [detail, setDetail] = useState<Workout | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [muscleFilter, setMuscleFilter] = useState<Muscle | 'all'>('all');
  const [equipmentFilter, setEquipmentFilter] = useState<Equipment | 'all'>('all');
  const [selectedMuscle, setSelectedMuscle] = useState<Muscle | null>(null);
  const [weekOffset, setWeekOffset] = useState(0);
  const [minutes, setMinutes] = useState(40);
  const [planEquipment, setPlanEquipment] = useState<Equipment>('gym');
  const [excluded, setExcluded] = useState<Muscle[]>([]);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');
  const [progressExercise, setProgressExercise] = useState('bench');
  const [historySearch, setHistorySearch] = useState('');
  const [settingsDraft, setSettingsDraft] = useState<Settings>(DEFAULT_SETTINGS);
  const [exerciseDetail, setExerciseDetail] = useState<string | null>(null);

  const load = useCallback(async (signal?: AbortSignal) => {
    setLoading(true); setLoadError('');
    try { const data = await api<{ workouts: Workout[]; settings: Settings }>('/api/data', 'GET', undefined, signal); setWorkouts(data.workouts); setSettings(data.settings); setPlanEquipment(data.settings.equipment); setDemo(data.workouts.length === 0); }
    catch (e) { if (e instanceof Error && e.name !== 'AbortError') setLoadError(e.message); }
    finally { if (!signal?.aborted) setLoading(false); }
  }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  useEffect(() => { try { if (draft) localStorage.setItem('tyaga-draft-v1', JSON.stringify(draft)); else localStorage.removeItem('tyaga-draft-v1'); } catch { /* Finished workouts still save when browser storage is unavailable. */ } }, [draft]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 4500); return () => clearTimeout(id); }, [toast]);
  const demoData = useMemo(() => demoWorkouts(), []);
  const displayed = demo ? demoData : workouts;
  const anchor = useMemo(() => { const d = new Date(); d.setDate(d.getDate() + weekOffset * 7); return weekStart(d); }, [weekOffset]);
  const weekEnd = useMemo(() => { const d = new Date(anchor + 'T12:00:00'); d.setDate(d.getDate() + 6); return localDate(d); }, [anchor]);
  const weekWorkouts = useMemo(() => displayed.filter(w => w.date >= anchor && w.date <= weekEnd), [displayed, anchor, weekEnd]);
  const currentWeek = useMemo(() => displayed.filter(w => w.date >= weekStart() && w.date <= localDate()), [displayed]);
  const loads = useMemo(() => muscleLoad(weekWorkouts, settings), [weekWorkouts, settings]);
  const currentLoads = useMemo(() => muscleLoad(currentWeek, settings), [currentWeek, settings]);
  const realLoads = useMemo(() => muscleLoad(workouts.filter(w => w.date >= weekStart() && w.date <= localDate()), settings), [workouts, settings]);
  const plan = useMemo(() => buildBalancePlan(currentLoads, minutes, planEquipment, excluded), [currentLoads, minutes, planEquipment, excluded]);
  const lowMuscles = [...loads].sort((a, b) => a.ratio - b.ratio).filter(m => m.ratio < 0.8);
  const monthWorkouts = displayed.filter(w => { const d = new Date(); d.setDate(d.getDate() - 27); return w.date >= localDate(d) && w.date <= localDate(); });
  const go = (v: View) => { setView(v); setMobileNav(false); window.scrollTo({ top: 0, behavior: 'instant' }); };
  const start = (ids: string[] = [], name?: string) => {
    if (draft) { go('workout'); setToast('У тебя уже есть черновик. Продолжи или отмени его.'); setModal(null); return; }
    const workout = makeWorkout(ids, workouts); if (name) workout.name = name;
    setDraft({ workout, startedAt: Date.now(), editing: false }); setDemo(false); setSaveError(''); setModal(null); go('workout');
  };
  const addExercise = (id: string) => {
    if (!draft) { start([id]); return; }
    if (draft.workout.exercises.some(e => e.exerciseId === id) || draft.workout.exercises.length >= 30) return;
    const last = [...workouts].sort((a, b) => b.date.localeCompare(a.date)).flatMap(w => w.exercises).find(e => e.exerciseId === id)?.sets.find(s => s.done && !s.warmup);
    setDraft(d => d ? { ...d, workout: { ...d.workout, exercises: [...d.workout.exercises, { exerciseId: id, sets: makeSets(3, last?.weight ?? 0, last?.reps ?? 10) }] } } : null);
    setToast('Упражнение добавлено');
  };
  const openPicker = () => { if (!draft) start(); setSearch(''); setMuscleFilter('all'); setEquipmentFilter('all'); setModal('picker'); };
  const saveWorkout = async () => {
    if (!draft || saving) return; setSaving(true); setSaveError('');
    const workout = { ...draft.workout, duration: draft.editing ? draft.workout.duration : Math.min(1440, Math.round((Date.now() - draft.startedAt) / 60000)) };
    try { const result = await api<{ workout: Workout }>('/api/workouts', 'PUT', workout); setWorkouts(ws => [result.workout, ...ws.filter(w => w.id !== result.workout.id)].sort((a, b) => b.date.localeCompare(a.date))); setDraft(null); setDemo(false); go('history'); setToast(draft.editing ? 'Изменения сохранены' : 'Тренировка сохранена. Хорошая работа!'); }
    catch (e) { setSaveError(e instanceof Error ? e.message : 'Ошибка сохранения'); } finally { setSaving(false); }
  };
  const editWorkout = (w: Workout) => { if (demo) return; if (draft) { setDetail(null); go('workout'); setToast('Сначала заверши или отмени текущий черновик.'); return; } setDraft({ workout: structuredClone(w), startedAt: Date.now(), editing: true }); setSaveError(''); setDetail(null); go('workout'); };
  const deleteWorkout = async () => { if (!deleteId || saving) return; setSaving(true); try { await api('/api/workouts/' + encodeURIComponent(deleteId), 'DELETE'); setWorkouts(ws => ws.filter(w => w.id !== deleteId)); setDeleteId(null); setDetail(null); setToast('Тренировка удалена'); } catch (e) { setToast(e instanceof Error ? e.message : 'Ошибка удаления'); } finally { setSaving(false); } };
  const exportHistory = () => { const blob = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), workouts, settings }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `tyaga-${localDate()}.json`; a.click(); URL.revokeObjectURL(url); setToast('Твои данные выгружены. Примеры в файл не входят.'); };
  const saveSettings = async () => { setSaving(true); setSaveError(''); try { const result = await api<{ settings: Settings }>('/api/settings', 'PUT', settingsDraft); setSettings(result.settings); setPlanEquipment(result.settings.equipment); setModal(null); setToast('Цели обновлены'); } catch (e) { setSaveError(e instanceof Error ? e.message : 'Ошибка сохранения'); } finally { setSaving(false); } };
  const openSettings = () => { setSettingsDraft(structuredClone(settings)); setSaveError(''); setModal('settings'); };
  const filteredExercises = EXERCISES.filter(e => e.name.toLowerCase().includes(search.toLowerCase()) && (muscleFilter === 'all' || [...e.primary, ...e.secondary].includes(muscleFilter)) && (equipmentFilter === 'all' || equipmentFilter === 'gym' || e.equipment === equipmentFilter || e.equipment === 'bodyweight'));
  const historyFiltered = displayed.filter(w => `${w.name} ${w.exercises.map(e => exerciseById(e.exerciseId)?.name).join(' ')}`.toLowerCase().includes(historySearch.toLowerCase()));
  const progressPoints = displayed.filter(w => w.exercises.some(e => e.exerciseId === progressExercise)).sort((a, b) => a.date.localeCompare(b.date)).map(w => {
    const sets = w.exercises.find(e => e.exerciseId === progressExercise)!.sets.filter(s => s.done && !s.warmup);
    return { date: w.date, max: Math.max(0, ...sets.map(s => s.weight)), e1rm: Math.max(0, ...sets.map(s => estimatedOneRepMax(s) ?? 0)), reps: sets.reduce((n, s) => n + s.reps, 0), sets };
  });
  const lastProgress = progressPoints.at(-1);
  const firstProgress = progressPoints[0];
  useTrainingTools({ draft, workouts, loads: realLoads, stage: workout => { setDraft({ workout, startedAt: Date.now(), editing: false }); setDemo(false); setView('workout'); } });

  const exerciseFilters = <div className="exercise-filters"><div className="search-field"><Search size={18} /><input placeholder="Найти упражнение…" aria-label="Поиск упражнений" value={search} onChange={e => setSearch(e.target.value)} /></div><select aria-label="Фильтр по мышцам" value={muscleFilter} onChange={e => setMuscleFilter(e.target.value as Muscle | 'all')}><option value="all">Все мышцы</option>{MUSCLES.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><select aria-label="Фильтр по оборудованию" value={equipmentFilter} onChange={e => setEquipmentFilter(e.target.value as Equipment | 'all')}><option value="all">Любое оборудование</option>{Object.entries(EQ).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></div>;
  const exerciseCards = (picker = false) => <div className={picker ? 'picker-list' : 'library-grid'}>{filteredExercises.length ? filteredExercises.map((e, i) => <article key={e.id} className={picker ? 'picker-exercise' : 'library-card panel'}><div className="library-icon"><Dumbbell size={picker ? 18 : 24} /></div><div className="library-copy"><span className="tiny">{EQ[e.equipment]}</span><h3>{e.name}</h3><p>{e.primary.map(m => MUSCLES.find(x => x.id === m)!.short).join(' · ')}</p>{!picker ? <button className="text-button" onClick={() => setExerciseDetail(e.id)}>Техника упражнения</button> : null}</div><button className={picker ? 'icon-button add-exercise-button' : 'library-add'} disabled={!!draft?.workout.exercises.some(x => x.exerciseId === e.id) || (draft?.workout.exercises.length ?? 0) >= 30} aria-label={`Добавить ${e.name}`} onClick={() => addExercise(e.id)}>{draft?.workout.exercises.some(x => x.exerciseId === e.id) ? <Check size={20} /> : <Plus size={20} />}</button>{!picker ? <span className="library-index">{String(i + 1).padStart(2, '0')}</span> : null}</article>) : <div className="no-results">Не нашлось упражнений. Измени поиск или фильтр.</div>}</div>;
  const sessionItem = (w: Workout, expanded = false) => <button className="session-item" key={w.id} onClick={() => setDetail(w)}><div className="session-date"><b>{new Date(w.date + 'T12:00:00').getDate()}</b><span>{new Date(w.date + 'T12:00:00').toLocaleDateString('ru-RU', { month: 'short' }).replace('.', '')}</span></div><div className="session-item-info"><h3>{w.name}</h3><p>{w.exercises.length} упр. <span>·</span> {workingSets([w])} подходов {expanded ? <><span>·</span>{w.exercises.slice(0, 2).map(e => exerciseById(e.exerciseId)?.name).join(', ')}</> : null}</p></div><div className="session-item-value"><b>{fmt(volume([w]) / 1000)} т</b><span><Clock3 size={13} />{w.duration} мин</span></div><ChevronRight size={17} className="muted" /></button>;

  return <div className="app-shell">
    {mobileNav ? <button className="nav-scrim" aria-label="Закрыть меню" onClick={() => setMobileNav(false)} /> : null}
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><a className="brand" href="#" onClick={e => { e.preventDefault(); go('overview'); }}><span className="brand-mark"><Dumbbell size={26} strokeWidth={2.7} /></span><span>тяга<span className="brand-period">.</span></span></a><span className="sidebar-caption">ТРЕНИРОВОЧНЫЙ ЖУРНАЛ</span><nav aria-label="Основная навигация">{NAV.map(n => <button className={`nav-item ${view === n.id ? 'active' : ''}`} key={n.id} onClick={() => go(n.id)} aria-current={view === n.id ? 'page' : undefined}><n.icon size={20} /><span>{n.label}</span>{n.id === 'workout' && draft ? <i className="draft-dot" /> : null}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-motto"><div className="motto-line" /><b>Сильнее.<br />С каждым подходом.</b></div><button className="nav-item" onClick={openSettings}><Settings2 size={19} />Мои цели</button><button className="profile-button" onClick={openSettings}><span className="profile-avatar">Т</span><span><b>Твой профиль</b><small><ShieldCheck size={12} />Личный журнал</small></span><SlidersHorizontal size={16} /></button></div></aside>
    <main className="main-content"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Открыть меню" onClick={() => setMobileNav(true)}><Menu size={22} /></button><div className="breadcrumb">Мой зал<span>/</span><b>{NAV.find(n => n.id === view)!.label}</b></div><div className="topbar-right"><span className="local-date"><CalendarDays size={16} />{new Date().toLocaleDateString('ru-RU', { day: 'numeric', month: 'long', weekday: 'short' })}</span><button className="icon-button" aria-label="Настройки целей" onClick={openSettings}><Settings2 size={19} /></button></div></header>
    <div className="page-content"><div className="page-heading"><div><div className="eyebrow">{view === 'overview' ? 'МЕНЬШЕ ДОГАДОК. БОЛЬШЕ ПРОГРЕССА.' : 'ТВОЙ ТРЕНИРОВОЧНЫЙ ЖУРНАЛ'}</div><h1>{({ overview: 'Твой прогресс', workout: draft?.editing ? 'Редактировать тренировку' : 'Твоя тренировка', history: 'История тренировок', library: 'Библиотека упражнений', progress: 'Сила в цифрах' })[view]}</h1><p>{({ overview: 'Каждый подход складывается в результат.', workout: 'Записывай подходы. Остальное посчитаем.', history: 'Вся работа, которую ты уже сделал.', library: 'Найди упражнение для своей следующей тренировки.', progress: 'Сравнивай себя с собой. По одному упражнению за раз.' })[view]}</p></div>{view !== 'workout' ? <button className="button primary start-button" onClick={() => start()}><Plus size={19} />{draft ? 'Продолжить тренировку' : 'Начать тренировку'}</button> : null}</div>
      {loadError ? <div className="error-banner" role="alert"><Info size={18} /><span>{loadError}</span><button className="text-button" onClick={() => void load()}>Повторить</button></div> : null}
      {loading ? <div className="loading-state" role="status"><span className="loader" />Загружаем твой журнал…</div> : <>
      {demo && view !== 'workout' ? <div className="demo-banner"><span><Sparkles size={16} /><b>Пример данных</b><span className="demo-explanation">Так будет выглядеть твой прогресс. Эти тренировки не сохранены в твоём аккаунте.</span></span><button onClick={() => setDemo(false)}>Мои данные<X size={14} /></button></div> : null}
      {!demo && !workouts.length && view !== 'workout' ? <div className="intro-banner"><Dumbbell size={18} /><span>Здесь появится твоя история. Начни первую тренировку или посмотри, как работает журнал.</span><button className="text-button" onClick={() => setDemo(true)}>Посмотреть пример</button></div> : null}
      {view === 'overview' ? <>
        <div className="stats-grid"><Stat icon={<Dumbbell size={19} />} label="Тренировок" value={String(monthWorkouts.length).padStart(2, '0')} meta="за последние 28 дней" /><Stat icon={<BarChart3 size={19} />} label="Рабочих подходов" value={String(workingSets(weekWorkouts))} meta="за выбранную неделю" /><Stat icon={<TrendingUp size={19} />} label="Общий объём" value={fmt(volume(weekWorkouts) / 1000)} unit="т" meta="вес × повторы за неделю" /><Stat icon={<Target size={19} />} label="Баланс недели" value={String(balanceScore(loads))} unit="%" meta="от твоих целей по мышцам" accent /></div>
        <div className="overview-grid"><section className="panel muscle-panel"><div className="panel-header"><div><div className="card-eyebrow">ВИДЕТЬ ПОЛНУЮ КАРТИНУ</div><h2>Баланс мышц</h2></div><button className="icon-button" aria-label="Как считается нагрузка" onClick={() => setModal('method')}><Info size={18} /></button></div><div className="week-selector"><button className="icon-button" aria-label="Предыдущая неделя" onClick={() => setWeekOffset(o => o - 1)}><ChevronLeft size={18} /></button><span>{dateLabel(anchor)} — {dateLabel(weekEnd)}<small>{weekOffset === 0 ? 'Эта неделя' : 'Выбранная неделя'}</small></span><button className="icon-button" aria-label="Следующая неделя" disabled={weekOffset >= 0} onClick={() => setWeekOffset(o => o + 1)}><ChevronRight size={18} /></button></div><div className="muscle-content"><BodyMap loads={loads} selected={selectedMuscle} onSelect={setSelectedMuscle} /><div className="muscle-list"><div className="muscle-list-label"><span>МЫШЦА</span><span>ПОДХОДЫ / ЦЕЛЬ</span></div>{loads.map(m => <button key={m.id} className={`muscle-row ${selectedMuscle === m.id ? 'selected' : ''}`} onClick={() => setSelectedMuscle(m.id)}><div className="muscle-row-heading"><span>{m.short}</span><b>{fmt(m.total)}<small> / {m.goal}</small></b></div><div className="load-track"><span style={{ width: `${Math.min(m.ratio, 1) * 100}%`, background: loadColor(m.ratio) }} /></div></button>)}{selectedMuscle ? <div className="muscle-detail"><b>{loads.find(m => m.id === selectedMuscle)!.name}</b><p>{fmt(loads.find(m => m.id === selectedMuscle)!.direct)} прямых + {fmt(loads.find(m => m.id === selectedMuscle)!.indirect)} косвенных подходов</p></div> : <p className="map-instruction">Выбери мышцу, чтобы увидеть детали.</p>}</div></div><div className="muscle-footnote"><span className="tiny">Нагрузка по журналу, а не оценка силы или роста мышц.</span><button className="text-button" onClick={openSettings}>Настроить цели</button></div></section>
        <aside className="focus-column"><section className="focus-card"><div className="focus-top"><span className="feature-tag"><Sparkles size={14} />БАЛАНС НЕДЕЛИ</span><Target size={22} /></div><h2>{lowMuscles.length ? 'Закрой пробелы. Без лишнего.' : 'Баланс — в твоих руках.'}</h2><p>{lowMuscles.length ? `Меньше всего нагрузки: ${lowMuscles.slice(0, 2).map(m => m.short.toLowerCase()).join(' и ')}. Соберём короткую тренировку с понятным «почему».` : 'Недельные цели по мышцам достигнуты. Можно пересмотреть цели или дать себе время на отдых.'}</p><div className="focus-muscles">{lowMuscles.slice(0, 3).map(m => <span key={m.id}>{m.short}<b>{fmt(m.total)} / {m.goal}</b></span>)}</div><button className="button focus-button" onClick={() => { setExcluded([]); setModal('planner'); }}>Собрать тренировку<SlidersHorizontal size={17} /></button><span className="focus-note">По нагрузке и доступному времени</span></section>
        <section className="panel week-card"><div className="panel-header"><h3>Твоя неделя</h3><CalendarDays size={17} className="muted" /></div><div className="week-days">{Array.from({ length: 7 }, (_, i) => { const d = new Date(anchor + 'T12:00:00'); d.setDate(d.getDate() + i); const date = localDate(d); const trained = weekWorkouts.some(w => w.date === date); return <div className={`week-day ${trained ? 'trained' : ''} ${date === localDate() ? 'today' : ''}`} key={i}><span>{['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'][i]}</span><b>{trained ? <Check size={15} /> : d.getDate()}</b></div>; })}</div><div className="week-card-footer"><span><i className="training-dot" />Тренировочные дни</span><b>{weekWorkouts.length}</b></div></section><section className="quiet-tip"><Flame size={19} /><p>Рост — это нагрузка,<br />восстановление и постоянство.</p></section></aside></div>
        <div className="bottom-grid"><section className="panel volume-panel"><div className="panel-header"><div><h2>Работа в цифрах</h2><p>Объём тренировок · вес × повторы</p></div><span className="period-label">28 дней</span></div><VolumeChart workouts={monthWorkouts} /><div className="chart-footer"><span><i />Объём за день</span><b>{fmt(volume(monthWorkouts) / 1000)} т<span> всего</span></b></div></section><section className="panel recent-panel"><div className="panel-header"><h2>Последние тренировки</h2><button className="text-button" onClick={() => go('history')}>Все</button></div>{displayed.slice(0, 3).map(w => sessionItem(w))}{!displayed.length ? <div className="small-empty">Первый подход — начало истории.<button className="text-button" onClick={() => start()}>Записать тренировку</button></div> : null}</section></div>
      </> : null}
      {view === 'workout' ? <WorkoutView draft={draft} update={setDraft} settings={settings} saving={saving} error={saveError} onPick={openPicker} onSave={() => void saveWorkout()} onDiscard={() => setModal('discard')} /> : null}
      {view === 'history' ? <><div className="history-toolbar"><div className="search-field"><Search size={18} /><input aria-label="Поиск по истории" placeholder="Название или упражнение…" value={historySearch} onChange={e => setHistorySearch(e.target.value)} /></div><button className="button secondary" onClick={exportHistory}><Download size={17} />Экспорт JSON</button></div><div className="panel history-panel">{historyFiltered.map(w => sessionItem(w, true))}{!displayed.length ? <div className="empty-state"><History size={36} /><h2>История начинается сегодня</h2><p>Завершённая тренировка появится здесь — с каждым подходом.</p><button className="button primary" onClick={() => start()}>Записать тренировку</button></div> : null}{displayed.length && !historyFiltered.length ? <div className="no-results">Таких тренировок пока нет.</div> : null}</div></> : null}
      {view === 'library' ? <>{exerciseFilters}<div className="library-header"><span>{filteredExercises.length} упражнений</span><span>Нажми «+», чтобы добавить в тренировку</span></div>{exerciseCards()}</> : null}
      {view === 'progress' ? <><div className="progress-selector"><label>Упражнение<select value={progressExercise} onChange={e => setProgressExercise(e.target.value)}>{EXERCISES.map(e => <option value={e.id} key={e.id}>{e.name}</option>)}</select></label><p>Расчётный максимум показан только для подходов от 1 до 12 повторений с весом.</p></div><div className="stats-grid progress-stats"><Stat icon={<Trophy size={19} />} label="Лучший рабочий вес" value={fmt(Math.max(0, ...progressPoints.map(p => p.max)))} unit="кг" meta="по выполненным подходам" /><Stat icon={<TrendingUp size={19} />} label="Изменение веса" value={lastProgress && firstProgress ? `${lastProgress.max - firstProgress.max >= 0 ? '+' : ''}${fmt(lastProgress.max - firstProgress.max)}` : '—'} unit={lastProgress ? 'кг' : ''} meta="первая → последняя тренировка" /><Stat icon={<Target size={19} />} label="Расчётный 1ПМ" value={lastProgress?.e1rm ? fmt(lastProgress.e1rm) : '—'} unit={lastProgress?.e1rm ? 'кг' : ''} meta="оценка по формуле Эпли" /><Stat icon={<CalendarDays size={19} />} label="Тренировок" value={String(progressPoints.length)} meta="с этим упражнением" /></div><section className="panel progress-panel"><div className="panel-header"><div><h2>{exerciseById(progressExercise)!.name}</h2><p>Максимальный вес в каждой тренировке</p></div><span className="chart-key"><i />Рабочий вес</span></div>{progressPoints.length ? <><div className="large-sparkline"><Sparkline values={progressPoints.map(p => p.max)} /></div><div className="progress-dates"><span>{dateLabel(firstProgress.date, true)}</span><span>{dateLabel(lastProgress!.date, true)}</span></div><div className="progress-history">{[...progressPoints].reverse().map((p, i) => <div key={`${p.date}-${i}`}><span>{dateLabel(p.date, true)}</span><span>{p.sets.length} подходов · {p.reps} повторов</span><b>{fmt(p.max)} кг</b></div>)}</div></> : <div className="empty-state"><TrendingUp size={34} /><h2>Прогрессу нужна точка отсчёта</h2><p>Запиши {exerciseById(progressExercise)!.name.toLowerCase()} в тренировке, чтобы увидеть динамику.</p><button className="button primary" onClick={() => start([progressExercise])}>Записать упражнение</button></div>}</section></> : null}
      </>}
      <footer className="page-footer"><span>тяга<span>.</span></span><p>Твоя работа. Твои данные. Твой результат.</p><button onClick={() => setModal('method')}>Как мы считаем</button></footer></div>
    </main>
    {toast ? <div className="toast" role="status"><Check size={17} /><span>{toast}</span><button className="icon-button" aria-label="Скрыть уведомление" onClick={() => setToast('')}><X size={16} /></button></div> : null}
    {modal === 'picker' ? <Modal title="Добавить упражнения" onClose={() => setModal(null)} wide>{exerciseFilters}{exerciseCards(true)}<div className="modal-actions"><span className="muted">{draft?.workout.exercises.length ?? 0} упражнений в тренировке</span><button className="button primary" onClick={() => { setModal(null); go('workout'); }}>Готово</button></div></Modal> : null}
    {modal === 'planner' ? <Modal title="Баланс недели" onClose={() => setModal(null)} wide><p className="modal-intro">Добавим нагрузку туда, где её меньше твоей цели. План учитывает {demo ? 'пример тренировок' : 'твой журнал'} за текущую неделю.</p><div className="planner-controls"><div><label>Сколько времени есть?</label><div className="segmented">{[20, 40, 60].map(n => <button key={n} className={minutes === n ? 'active' : ''} onClick={() => setMinutes(n)}>{n} мин</button>)}</div></div><label>Оборудование<select value={planEquipment} onChange={e => setPlanEquipment(e.target.value as Equipment)}>{Object.entries(EQ).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label></div><details className="exclude-muscles"><summary>Какие мышцы пропустить сегодня?</summary><p className="tiny">Выбранные мышцы не попадут ни в прямую, ни в косвенную нагрузку.</p><div className="muscle-chips">{MUSCLES.map(m => <label key={m.id}><input type="checkbox" checked={excluded.includes(m.id)} onChange={e => setExcluded(xs => e.target.checked ? [...xs, m.id] : xs.filter(id => id !== m.id))} />{m.short}</label>)}</div></details><div className="balance-projection"><div><span>Баланс сейчас</span><b>{plan.before}%</b></div><div className="projection-divider" /><div><span>Если выполнить план</span><b>{plan.after}%</b></div><span className="projection-change">+{plan.after - plan.before} п.п.</span></div><div className="plan-list">{plan.picks.map((p, i) => <div className="plan-item" key={p.exercise.id}><span className="exercise-number">{String(i + 1).padStart(2, '0')}</span><div><h3>{p.exercise.name}</h3><span>3 подхода × 8–12 повторений · RIR 2</span><p><Sparkles size={13} />{p.reason}</p></div></div>)}{!plan.picks.length ? <div className="no-results">Нет подходящих пробелов. Выбери другое оборудование, сними исключения или запланируй отдых.</div> : null}</div><p className="tiny planner-disclaimer">Прогноз предполагает выполнение всех подходов с RIR 0–3. Время приблизительное. Рабочий вес выбери по самочувствию; при боли пропусти упражнение.</p><div className="modal-actions"><span className="muted"><Clock3 size={16} />Около {plan.minutes} минут</span><button className="button primary" disabled={!plan.picks.length} onClick={() => start(plan.picks.map(p => p.exercise.id), 'Баланс недели')}><Plus size={17} />{demo ? 'Попробовать этот план' : 'Начать по плану'}</button></div></Modal> : null}
    {modal === 'settings' ? <Modal title="Твои цели" onClose={() => setModal(null)}><p className="modal-intro">Недельные ориентиры для баланса. Это редактируемые цели по нагрузке, а не персональная программа.</p><div className="goal-settings">{MUSCLES.map(m => <label key={m.id}><span>{m.name}</span><input aria-label={`Недельная цель: ${m.name}`} type="number" min="1" max="40" value={settingsDraft.goals[m.id]} onChange={e => setSettingsDraft(s => ({ ...s, goals: { ...s.goals, [m.id]: Number(e.target.value) } }))} /><span className="tiny">подх.</span></label>)}</div><div className="settings-bottom"><label>Оборудование<select value={settingsDraft.equipment} onChange={e => setSettingsDraft(s => ({ ...s, equipment: e.target.value as Equipment }))}>{Object.entries(EQ).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>Отдых, секунды<input type="number" min="15" max="600" step="15" value={settingsDraft.restSeconds} onChange={e => setSettingsDraft(s => ({ ...s, restSeconds: Number(e.target.value) }))} /></label></div>{saveError ? <p className="inline-error" role="alert">{saveError}</p> : null}<div className="modal-actions"><button className="text-button" onClick={() => setSettingsDraft(structuredClone(DEFAULT_SETTINGS))}>Сбросить к исходным</button><button className="button primary" disabled={saving} onClick={() => void saveSettings()}>{saving ? 'Сохраняем…' : 'Сохранить цели'}</button></div></Modal> : null}
    {modal === 'method' ? <Modal title="Понятный расчёт нагрузки" onClose={() => setModal(null)}><div className="method-content"><p>Карта показывает <b>объём записанной работы</b> по мышцам. Она не определяет силу, размер мышц или фактическое восстановление.</p><div className="formula-card"><b>1 прямой подход + 0,5 косвенного</b><span>× коэффициент интенсивности</span></div><ul><li>Только выполненные подходы. Разминка не учитывается.</li><li>RIR 0–3: коэффициент 1; RIR 4–5: 0,75; RIR 6–10: 0,5.</li><li>Жим лёжа даёт нагрузку груди и половину подхода трицепсу и плечам.</li><li>Баланс — среднее выполнение целей по 10 группам мышц. Превышение одной цели не компенсирует пропуск другой.</li></ul><p>Связи упражнений с мышцами и коэффициенты — упрощённая модель для планирования. Цели можно менять под свою программу.</p><p><b>Расчётный 1ПМ:</b> вес × (1 + повторы / 30). Для одного повтора — сам вес. Не вычисляется для разминки, подходов без веса и более 12 повторений.</p><p className="tiny">Объём в килограммах не включает массу тела. Для упражнений без оборудования смотри подходы и повторы.</p></div></Modal> : null}
    {modal === 'discard' ? <Modal title={draft?.editing ? 'Отменить изменения?' : 'Отменить тренировку?'} onClose={() => setModal(null)}><p className="modal-intro">{draft?.editing ? 'Сохранённая тренировка останется в истории. Изменения в черновике будут потеряны.' : 'Черновик и незавершённые подходы будут удалены с этого устройства.'}</p><div className="modal-actions"><button className="button secondary" onClick={() => setModal(null)}>Продолжить</button><button className="button danger" onClick={() => { setDraft(null); setModal(null); setSaveError(''); }}>Отменить</button></div></Modal> : null}
    {detail ? <Modal title={detail.name} onClose={() => setDetail(null)} wide><div className="workout-detail-meta"><span><CalendarDays size={16} />{dateLabel(detail.date, true)}</span><span><Clock3 size={16} />{detail.duration} мин</span><span><Dumbbell size={16} />{fmt(volume([detail]))} кг</span></div>{detail.exercises.map(e => <div className="detail-exercise" key={e.exerciseId}><h3>{exerciseById(e.exerciseId)!.name}</h3><div className="detail-sets">{e.sets.filter(s => s.done).map(s => <span key={s.id}>{s.warmup ? 'Разминка · ' : ''}<b>{s.weight} кг × {s.reps}</b><small>RIR {s.rir}</small></span>)}</div></div>)}{detail.notes ? <p className="detail-notes">{detail.notes}</p> : null}<div className="modal-actions">{!demo ? <button className="text-button danger-text" onClick={() => setDeleteId(detail.id)}><Trash2 size={15} />Удалить</button> : <span className="tiny">Пример данных</span>}<div className="button-group"><button className="button secondary" onClick={() => { const ids = detail.exercises.map(e => e.exerciseId); const name = detail.name; setDetail(null); start(ids, name); }}>Повторить</button>{!demo ? <button className="button primary" onClick={() => editWorkout(detail)}>Редактировать</button> : null}</div></div></Modal> : null}
    {deleteId ? <Modal title="Удалить тренировку?" onClose={() => setDeleteId(null)}><p className="modal-intro">Подходы исчезнут из истории и расчётов. Это действие нельзя отменить.</p><div className="modal-actions"><button className="button secondary" onClick={() => setDeleteId(null)}>Оставить</button><button className="button danger" disabled={saving} onClick={() => void deleteWorkout()}>{saving ? 'Удаляем…' : 'Удалить'}</button></div></Modal> : null}
    {exerciseDetail ? <Modal title={exerciseById(exerciseDetail)!.name} onClose={() => setExerciseDetail(null)}><div className="exercise-technique"><div className="technique-icon"><Dumbbell size={38} /></div><p>{exerciseById(exerciseDetail)!.tip}</p><h3>Основная нагрузка</h3><p>{exerciseById(exerciseDetail)!.primary.map(m => MUSCLES.find(x => x.id === m)!.name).join(', ')}</p>{exerciseById(exerciseDetail)!.secondary.length ? <><h3>Косвенная нагрузка</h3><p>{exerciseById(exerciseDetail)!.secondary.map(m => MUSCLES.find(x => x.id === m)!.name).join(', ')}</p></> : null}<button className="button primary full-width" onClick={() => { addExercise(exerciseDetail); setExerciseDetail(null); go('workout'); }} disabled={!!draft?.workout.exercises.some(e => e.exerciseId === exerciseDetail)}>Добавить в тренировку</button></div></Modal> : null}
  </div>;
}

function Stat({ icon, label, value, unit, meta, accent = false }: { icon: ReactNode; label: string; value: string; unit?: string; meta: string; accent?: boolean }) {
  return <article className={`stat-card panel ${accent ? 'accent-stat' : ''}`}><div className="stat-top"><span>{label}</span><span className="stat-icon">{icon}</span></div><div className="stat-value">{value}{unit ? <span>{unit}</span> : null}</div><p>{meta}</p></article>;
}
